title: gr4n173
url: https://gr4n173.github.io
author: gr4n173
email: me.gr4n173@protonmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Hi there, I am nerd guy who loves everything in between Internet and Security and reach out to people teach about CyberSecurity. I like to play with electronics in my spare time so that I can automate my lifestyle . CTF | HTB | Reverse Engineering.
show_excerpts: false # set to true to show excerpts on the homepage


paginate: 5
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: bitbrain-github-io

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/
      icon: twitter-square
      color: cyan
    - url: https://gr4n173.github.io
      icon: itch-io
      color: red
    - url: https://github.com/gr4n173
      icon: github-square
      color: purple

# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
